### ISSUE TITLE
Fix Instructions

### ISSUE THREAD

**Issue by davops** [jpsider/PowerWamp#11]
The installation instructions need an update. The current link in the copy and paste section (https://raw.githubusercontent.com/jpsider/PowerWamp/master/powerWamp.psm1) gives a 404 because it doesn't exist at that path. 
```
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At line:5 char:3
+   $webclient.DownloadFile($url,$filepath)
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```
Also, the script errors because a local path is missing:
```
Get-ChildItem : Cannot find path 'C:\temp\public' because it does not exist.
At C:\temp\powerwamp.psm1:21 char:32
+ ... r -function (Get-ChildItem -Path "$PSScriptRoot\public\*.ps1").basena ...
```

I don't have permissions to push a fix to the repo so a possible fix would be:
```
### Copy and paste these lines. c:\temp\public needs to exist

      $webclient = New-Object System.Net.WebClient  
      $filepath = "C:\temp\powerwamp.psm1"  
      $url = "https://raw.github.com/jpsider/PowerWamp/master/PowerWamp/PowerWamp.psm1"
```

**Comment by jpsider** [comment]
Do you think it would be better to remove these instructions since it's available through the PowerShell Gallery? or are these still potentially useful instructions?

**Comment by davops** [comment]
In that case, I'd just provide a link to the page in the Gallery. There are some other inconsistencies, such as _Connect-MySQL_ not being an available function. Thus, I'd stick with the PS Gallery, which already has installation/module information rather than having to maintain it in both places.

**Comment by jpsider** [comment]
I think thats fair! I've updated the readme, let me know if you find anything else! thanks!!

**Comment by davops** [comment]
The Readme looks good. Thanks!
